#! /bin/sh
#Configuracion de pines
echo out > /sys/class/gpio/gpio39/direction
echo out > /sys/class/gpio/gpio38/direction
echo out > /sys/class/gpio/gpio25/direction
echo out > /sys/class/gpio/gpio16/direction
echo out > /sys/class/gpio/gpio19/direction
echo out > /sys/class/gpio/gpio26/direction
echo out > /sys/class/gpio/gpio27/direction
echo out > /sys/class/gpio/gpio24/direction

echo out > /sys/class/gpio/gpio14/direction
echo 1 > /sys/class/gpio/gpio14/value
echo 0 > /sys/class/gpio/gpio14/value

echo in > /sys/class/gpio/gpio17/direction
echo in > /sys/class/gpio/gpio28/direction
echo in > /sys/class/gpio/gpio15/direction

#Variables
varEstado=0
varAnterior=0
varGato=0
varRaton=-1
contRandom=0
varAleatoria="0 7 5 2 3 0 2 1 4 3 6 5 0 2 3 6 5 2 1 4 5 2 1 0 3 6 7 5 4 2 3 6 5 1 4 2 3 6 2 4 1 2 3 6 5 2 1 5 2 3 6 2 4 0"

#Apaga todos los leds.
proApagar(){
  echo 0 > /sys/class/gpio/gpio39/value
  echo 0 > /sys/class/gpio/gpio38/value
  echo 0 > /sys/class/gpio/gpio25/value
  echo 0 > /sys/class/gpio/gpio16/value
  echo 0 > /sys/class/gpio/gpio19/value
  echo 0 > /sys/class/gpio/gpio26/value
  echo 0 > /sys/class/gpio/gpio27/value
  echo 0 > /sys/class/gpio/gpio24/value
  echo 0 > /sys/class/gpio/gpio14/value
}

#Apaga el ratón 
offRaton(){

  case $1 in
    0) echo 0 > /sys/class/gpio/gpio39/value;;
    1) echo 0 > /sys/class/gpio/gpio38/value;;
    2) echo 0 > /sys/class/gpio/gpio25/value;;
    3) echo 0 > /sys/class/gpio/gpio16/value;;
    4) echo 0 > /sys/class/gpio/gpio19/value;;
    5) echo 0 > /sys/class/gpio/gpio26/value;;
    6) echo 0 > /sys/class/gpio/gpio27/value;;
    7) echo 0 > /sys/class/gpio/gpio24/value;;
  esac
}

# Enciende el ratón
onRaton(){

  case $1 in
    0) echo 1 > /sys/class/gpio/gpio39/value
       usleep 450000;;
    1) echo 1 > /sys/class/gpio/gpio38/value
       usleep 450000;;
    2) echo 1 > /sys/class/gpio/gpio25/value
       usleep 450000;;
    3) echo 1 > /sys/class/gpio/gpio16/value
       usleep 450000;;
    4) echo 1 > /sys/class/gpio/gpio19/value
       usleep 450000;;
    5) echo 1 > /sys/class/gpio/gpio26/value
       usleep 450000;;
    6) echo 1 > /sys/class/gpio/gpio27/value
       usleep 450000;;
    7) echo 1 > /sys/class/gpio/gpio24/value
       usleep 450000;;
  esac
}

#Verifica en que posición esta el ratón
estaPrendido(){

  v0=`cat /sys/class/gpio/gpio39/value`
  v1=`cat /sys/class/gpio/gpio38/value`
  v2=`cat /sys/class/gpio/gpio25/value`
  v3=`cat /sys/class/gpio/gpio16/value`
  v4=`cat /sys/class/gpio/gpio19/value`
  v5=`cat /sys/class/gpio/gpio26/value`
  v6=`cat /sys/class/gpio/gpio27/value`
  v7=`cat /sys/class/gpio/gpio24/value`

  if [ $v0 == 1  ] && [ $varRaton == 0 ]; then
     return 0
  fi
  if [ $v1 == 1 ] && [ $varRaton == 1 ]; then
     return 1
  fi
  if [ $v2 == 1 ] && [ $varRaton == 2 ]; then
     return 2
  fi
  if [ $v3 == 1 ] && [ $varRaton == 3 ]; then
     return 3
  fi
  if [ $v4 == 1 ] && [ $varRaton == 4 ]; then
     return 4
  fi
  if [ $v5 == 1 ] && [ $varRaton == 5 ]; then
     return 5
  fi
  if [ $v6 == 1 ] && [ $varRaton == 6 ]; then
     return 6
  fi
  if [ $v7 == 1 ] && [ $varRaton == 7 ]; then
     return 7
  fi

}
funGenerarRandom(){
 contAux=0
 for i in $varAleatoria
 do
    if [ $contRandom != 51 ]; then
       if [ $contAux == $contRandom ]; then
          contRandom=$(($contRandom + 1))
          if [ $i != $varGato ]; then
             return $i
             break
          else
             continue
          fi
       else
           contAux=$(($contAux + 1))
       fi
    else
       contRandom=0
    fi
 done
}
#Mueve el gato a la derecha
movDerecha(){
   case $1 in
                1)
                        echo 0 > /sys/class/gpio/gpio39/value
                        echo 1 > /sys/class/gpio/gpio38/value;;
                2)
                        echo 0 > /sys/class/gpio/gpio38/value
                        echo 1 > /sys/class/gpio/gpio25/value;;
                3)
                        echo 0 > /sys/class/gpio/gpio25/value
                        echo 1 > /sys/class/gpio/gpio16/value;;
                4)
                        echo 0 > /sys/class/gpio/gpio16/value
                        echo 1 > /sys/class/gpio/gpio19/value;;
                5)
                        echo 0 > /sys/class/gpio/gpio19/value
                        echo 1 > /sys/class/gpio/gpio26/value;;
                6)
                        echo 0 > /sys/class/gpio/gpio26/value
                        echo 1 > /sys/class/gpio/gpio27/value;;
                7)
                        echo 0 > /sys/class/gpio/gpio27/value
                        echo 1 > /sys/class/gpio/gpio24/value;;
                *)
                        varGato=0
                        echo 0 > /sys/class/gpio/gpio24/value
                        echo 1 > /sys/class/gpio/gpio39/value;;
   esac
}
#Mueve el gato a la izquierda 
movIzquierda(){
   case $1 in
                0)
                        echo 1 > /sys/class/gpio/gpio39/value
                        echo 0 > /sys/class/gpio/gpio38/value;;
                1)
                        echo 1 > /sys/class/gpio/gpio38/value
                        echo 0 > /sys/class/gpio/gpio25/value;;
                2)
                        echo 1 > /sys/class/gpio/gpio25/value
                        echo 0 > /sys/class/gpio/gpio16/value;;
                3)
                        echo 1 > /sys/class/gpio/gpio16/value
                        echo 0 > /sys/class/gpio/gpio19/value;;
                4)
                        echo 1 > /sys/class/gpio/gpio19/value
                        echo 0 > /sys/class/gpio/gpio26/value;;
                5)
                        echo 1 > /sys/class/gpio/gpio26/value
                        echo 0 > /sys/class/gpio/gpio27/value;;
                6)
                        echo 1 > /sys/class/gpio/gpio27/value
                        echo 0 > /sys/class/gpio/gpio24/value;;
                *)
                        varGato=7
                        echo 1 > /sys/class/gpio/gpio24/value
                        echo 0 > /sys/class/gpio/gpio39/value;;
   esac
}


pulsadorIzq(){
while (true)
do
  varEstado=`cat /sys/class/gpio/gpio28/value`

        if [ $varEstado != $varAnterior ]; then
                if [ $varEstado == 0 ]; then
                    varGato=$(($varGato - 1))
                    movIzquierda $varGato
                    if [ $varGato == $varRaton ]; then
                       echo 1 > /sys/class/gpio/gpio14/value
                       usleep 500000
                       echo 0 > /sys/class/gpio/gpio14/value
                    fi
                    break
                fi
        fi

  varAnterior=$varEstado
  
#Movimientos del ratón
  funGenerarRandom
  varRaton=$?
  onRaton $varRaton
  estaPrendido
  ratonAux=$?
  offRaton $ratonAux
done
}
pulsadorDer(){
while (true)
do
  varEstado=`cat /sys/class/gpio/gpio15/value`

        if [ $varEstado != $varAnterior ]; then
                if [ $varEstado == 0 ]; then
                    varGato=$(($varGato + 1))
                    movDerecha $varGato
                    if [ $varGato == $varRaton ]; then
                       echo 1 > /sys/class/gpio/gpio14/value
                       usleep 500000
                       echo 0 > /sys/class/gpio/gpio14/value
                    fi
                    break
                fi
        fi

  varAnterior=$varEstado
  
#Movimiento del ratón
  funGenerarRandom
  varRaton=$?
  onRaton $varRaton
  estaPrendido
  ratonAux=$?
  offRaton $ratonAux
done
}

#Enciende todos los leds.
prender(){
  echo 1 > /sys/class/gpio/gpio39/value
  echo 1 > /sys/class/gpio/gpio38/value
  echo 1 > /sys/class/gpio/gpio25/value
  echo 1 > /sys/class/gpio/gpio16/value
  echo 1 > /sys/class/gpio/gpio19/value
  echo 1 > /sys/class/gpio/gpio26/value
  echo 1 > /sys/class/gpio/gpio27/value
  echo 1 > /sys/class/gpio/gpio24/value
  echo 1 > /sys/class/gpio/gpio14/value
  usleep 300000
}


pulsadorReset(){
while true
do
   varEstado=`cat /sys/class/gpio/gpio17/value`

 if [ $varEstado != $varAnterior ]; then
        if [ $varEstado == 0 ]; then
           proApagar
           usleep 350000
           prender
           usleep 200000
           proApagar
           usleep 200000
           prender
           usleep 200000
           proApagar
           usleep 200000
           prender
           usleep 200000
           proApagar
           varGato=0
           echo 1 > /sys/class/gpio/gpio39/value
           break
        fi
    fi
   varAnterior=$varEstado
done
}

#Enciende el Gato
proApagar
echo 1 > /sys/class/gpio/gpio39/value

while true
do
   
   pul3=`cat /sys/class/gpio/gpio15/value`
   echo "Der:    " $pul3
   pul2=`cat /sys/class/gpio/gpio28/value`
   echo "Izq:    " $pul2
   pul1=`cat /sys/class/gpio/gpio17/value`
   echo "Reset:  " $pul1

   if [ $pul3 == 1 ]; then
      pulsadorDer
   elif [ $pul2 == 1 ]; then
      pulsadorIzq
   elif [ $pul1 == 1 ]; then
      pulsadorReset
   fi

   funGenerarRandom
   varRaton=$?
   onRaton $varRaton
   estaPrendido
   ratonAux=$?
   offRaton $ratonAux
done

